server:
  port: 8182
  servlet:
    context-path: /flance-saas
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flance_saas?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:flance/saas/sys/sql/*/*.xml,classpath:flance/saas/app/sql/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl